In [1]:
import pandas as pd
import numpy as np
print(f"pandas version:{pd.__version__}")

pandas version:3.0.6

In [2]:
data = {"PRODUCTS":["A","B","C","D"],
        "SALES":[1000,800,1200,750],
        "PROFIT":[200,150,300,1000]}
df = pd.DataFrame(data)
print("\nSample DataFrame:")
display(df)

Sample DataFrame:

  PRODUCTS  SALES  PROFIT
0        A   1000     200
1        B    800     150
2        C   1200     300
3        D    750    1000

In [3]:
temp = pd .Series([72,68,75,80],name = "Tempereature")
print("Series explample:")
print(temp)

Series explample:
0    72
1    68
2    75
3    80
Name: Tempereature, dtype: int64

In [4]:
import pandas as pd 
data = {"city":["NY","LA","chicago"]}
print(pd.Series(data))

city    [NY, LA, chicago]
dtype: object

In [5]:
import pandas as pd 
data = {"city":["NY","LA","chicago"],
       "Populataion":[8.4,3.9,2.7],
       "Area":[783.8,1302,606.1]}
cities = pd.DataFrame(data)
print("\nDataFrame example:")
display(cities)

DataFrame example:

      city  Populataion    Area
0       NY          8.4   783.8
1       LA          3.9  1302.0
2  chicago          2.7   606.1

In [6]:
print("\nDataFrame shape:",cities.shape)
print("Coloumns:",cities.columns)
print("Coloumns:",cities.columns.tolist())

DataFrame shape: (3, 3)
Coloumns: Index(['city', 'Populataion', 'Area'], dtype='str')
Coloumns: ['city', 'Populataion', 'Area']

In [7]:
import numpy as np

In [8]:
pd.date_range("20230101",periods = 6,freq = 'MS')

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01'],
              dtype='datetime64[us]', freq='MS')

In [9]:
dates = pd.date_range("20230101",periods = 6)
df = pd.DataFrame(np.random.randn(6,4),index = dates,columns = list("ABCD"))
df

                   A         B         C         D
2023-01-01  0.309136  0.820321  0.269530  0.956214
2023-01-02  0.913602  2.319870  0.726279 -0.150655
2023-01-03  0.002243 -0.641549 -0.053243 -0.227130
2023-01-04 -0.212491  1.204293 -0.741493 -1.491026
2023-01-05 -0.994140  1.742651  0.987622 -1.106324
2023-01-06 -0.259973  0.908686  0.214876  0.043087

In [10]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2023-01-01 to 2023-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.040270  1.059045  0.233929 -0.329306
std    0.635856  1.004959  0.607619  0.870281
min   -0.994140 -0.641549 -0.741493 -1.491026
25%   -0.248102  0.842412  0.013787 -0.886525
50%   -0.105124  1.056490  0.242203 -0.188893
75%    0.232412  1.608062  0.612092 -0.005348
max    0.913602  2.319870  0.987622  0.956214

In [12]:
dates = pd.date_range("20230101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df.to_csv("sample_data.csv")

df.to_excel("sample_data.xlsx")
df.to_parquet("sample_data.parquet")

In [13]:
print("From CSV:")
display(pd.read_csv("sample_data.csv", index_col=0, parse_dates=True).head())

From CSV:

                   A         B         C         D
2023-01-01 -0.231746 -0.196860  1.235181 -0.151835
2023-01-02  0.003099  1.231685  1.178013 -1.229686
2023-01-03  1.305853 -0.735376  0.199273  1.909564
2023-01-04 -0.716159  0.356886 -0.097767  0.946097
2023-01-05  1.687975  0.871916 -0.998690 -0.408980

In [14]:
df =pd.read_csv("sample_data.csv")

In [15]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
titanic = pd.read_csv(url)
print("\nTitanic dataset:")
display(titanic)

Titanic dataset:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [16]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
titanic[:50]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
29,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
34,0,1,male,28.0,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
37,0,3,male,21.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
39,1,3,female,14.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
42,0,3,male,NaN,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
44,1,3,female,19.0,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
46,0,3,male,NaN,1,0,15.5000,Q,Third,man,True,NaN,Queenstown,no,False
47,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
48,0,3,male,NaN,2,0,21.6792,C,Third,man,True,NaN,Cherbourg,no,False
49,0,3,female,18.0,1,0,17.8000,S,Third,woman,False,NaN,Southampton,no,False

In [18]:
titanic["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [19]:
data = {"Name": ["Alice", "Bob", None, "Charlie", "David", "Alice"],
        "Age": [25, 32, 45, None, 28, 25],
        "Salary": [50000, 60000, 75000, 48000, None, 50000],
        "Department": ["HR", "Tech", "Tech", None, "Finance", "HR"]}
employees = pd.DataFrame(data)
print("Original data:")
display(employees)

Original data:

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  32.0  60000.0       Tech
2      NaN  45.0  75000.0       Tech
3  Charlie   NaN  48000.0        NaN
4    David  28.0      NaN    Finance
5    Alice  25.0  50000.0         HR

In [20]:
print("\nMissing values:")
display(employees.isna())

Missing values:

    Name    Age  Salary  Department
0  False  False   False       False
1  False  False   False       False
2   True  False   False       False
3  False   True   False        True
4  False  False    True       False
5  False  False   False       False

In [21]:
print("\nMissing values:")
display(employees.isna().sum())

Missing values:

Name          1
Age           1
Salary        1
Department    1
dtype: int64

In [22]:
clean_df = employees.copy()

In [23]:
employees

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  32.0  60000.0       Tech
2      NaN  45.0  75000.0       Tech
3  Charlie   NaN  48000.0        NaN
4    David  28.0      NaN    Finance
5    Alice  25.0  50000.0         HR

In [24]:
clean_df["Age"].mean()

np.float64(31.0)

In [25]:
clean_df = employees.copy()
clean_df["Age"] = clean_df["Age"].fillna(clean_df["Age"].mean())

In [26]:
clean_df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  32.0  60000.0       Tech
2      NaN  45.0  75000.0       Tech
3  Charlie  31.0  48000.0        NaN
4    David  28.0      NaN    Finance
5    Alice  25.0  50000.0         HR

In [27]:
clean_df.dropna(subset=["Department"],inplace= True)

In [28]:
clean_df

    Name   Age   Salary Department
0  Alice  25.0  50000.0         HR
1    Bob  32.0  60000.0       Tech
2    NaN  45.0  75000.0       Tech
4  David  28.0      NaN    Finance
5  Alice  25.0  50000.0         HR

In [29]:
clean_df.drop_duplicates(inplace=True)
print("\nCleaned data:")
display(clean_df)

Cleaned data:

    Name   Age   Salary Department
0  Alice  25.0  50000.0         HR
1    Bob  32.0  60000.0       Tech
2    NaN  45.0  75000.0       Tech
4  David  28.0      NaN    Finance

In [30]:
print("\nSalary stats:")
print(clean_df["Salary"].describe())

Salary stats:
count        3.000000
mean     61666.666667
std      12583.057392
min      50000.000000
25%      55000.000000
50%      60000.000000
75%      67500.000000
max      75000.000000
Name: Salary, dtype: float64

In [31]:
Q1 = clean_df["Salary"].quantile(0.25)
Q3 = clean_df["Salary"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print("Lower: ",lower_bound)
print("Upper: ",upper_bound)
outliers = clean_df[(clean_df["Salary"] < lower_bound) | (clean_df["Salary"] > upper_bound)]
print("Outliers:\n", outliers["Salary"])

Lower:  36250.0
Upper:  86250.0
Outliers:
 Series([], Name: Salary, dtype: float64)

In [32]:
clean_df["Name"] = clean_df["Name"].str.upper()
print("\nAfter string operations:")
display(clean_df)

After string operations:

    Name   Age   Salary Department
0  ALICE  25.0  50000.0         HR
1    BOB  32.0  60000.0       Tech
2    NaN  45.0  75000.0       Tech
4  DAVID  28.0      NaN    Finance

In [33]:
import pandas as pd
import numpy as npta
np.random.seed(42)
dates = pd.date_range("20230101", periods=10)
df = pd.DataFrame({
"A": np.random.randn(10),
"B": np.random.randint(1, 100, 10),
"C": np.random.choice(["X", "Y", "Z"], 10),
"D": dates
}).set_index("D")
print("Sample data:")
display(df)

Sample data:

                   A   B  C
D
2023-01-01  0.496714  64  Z
2023-01-02 -0.138264  60  Z
2023-01-03  0.647689  21  Y
2023-01-04  1.523030  33  Z
2023-01-05 -0.234153  76  Y
2023-01-06 -0.234137  58  Y
2023-01-07  1.579213  22  Z
2023-01-08  0.767435  89  Y
2023-01-09 -0.469474  49  Z
2023-01-10  0.542560  91  Z

In [34]:
print("\nColumn selection:")
print(df["A"].head())  
print(df[["A", "C"]].head())

Column selection:
D
2023-01-01    0.496714
2023-01-02   -0.138264
2023-01-03    0.647689
2023-01-04    1.523030
2023-01-05   -0.234153
Name: A, dtype: float64
                   A  C
D
2023-01-01  0.496714  Z
2023-01-02 -0.138264  Z
2023-01-03  0.647689  Y
2023-01-04  1.523030  Z
2023-01-05 -0.234153  Y

In [35]:
df

                   A   B  C
D
2023-01-01  0.496714  64  Z
2023-01-02 -0.138264  60  Z
2023-01-03  0.647689  21  Y
2023-01-04  1.523030  33  Z
2023-01-05 -0.234153  76  Y
2023-01-06 -0.234137  58  Y
2023-01-07  1.579213  22  Z
2023-01-08  0.767435  89  Y
2023-01-09 -0.469474  49  Z
2023-01-10  0.542560  91  Z

In [36]:
print("\nRow selection:")
print(df.iloc[2:5])  
print(df.loc["2023-01-03":"2023-01-06"])

Row selection:
                   A   B  C
D
2023-01-03  0.647689  21  Y
2023-01-04  1.523030  33  Z
2023-01-05 -0.234153  76  Y
                   A   B  C
D
2023-01-03  0.647689  21  Y
2023-01-04  1.523030  33  Z
2023-01-05 -0.234153  76  Y
2023-01-06 -0.234137  58  Y

In [37]:
print("\nBoolean indexing:")
print(df[df["B"] > 50])

Boolean indexing:
                   A   B  C
D
2023-01-01  0.496714  64  Z
2023-01-02 -0.138264  60  Z
2023-01-05 -0.234153  76  Y
2023-01-06 -0.234137  58  Y
2023-01-08  0.767435  89  Y
2023-01-10  0.542560  91  Z

In [38]:
print(df[(df["B"] > 30) | (df["C"] == "X")])

                   A   B  C
D
2023-01-01  0.496714  64  Z
2023-01-02 -0.138264  60  Z
2023-01-04  1.523030  33  Z
2023-01-05 -0.234153  76  Y
2023-01-06 -0.234137  58  Y
2023-01-08  0.767435  89  Y
2023-01-09 -0.469474  49  Z
2023-01-10  0.542560  91  Z

In [39]:
print(df[(df["B"] > 30) & (df["C"] == "Y")])

                   A   B  C
D
2023-01-05 -0.234153  76  Y
2023-01-06 -0.234137  58  Y
2023-01-08  0.767435  89  Y

In [40]:
print("\nQuery method:")
print(df.query("A > 0 and C in ['X','Y']"))

Query method:
                   A   B  C
D
2023-01-03  0.647689  21  Y
2023-01-08  0.767435  89  Y

In [41]:
import pandas as pd
import numpy as np

sales = pd.DataFrame({
"Date": pd.date_range("2023-01-01", periods=10),
"Product": np.random.choice(["Widget", "Gadget", "Tool"], 10),
"Units": np.random.randint(1, 20, 10),
"Unit_Price": np.random.uniform(10, 50, 10).round(2)
})
sales

        Date Product  Units  Unit_Price
0 2023-01-01  Widget     14       46.37
1 2023-01-02    Tool     18       20.35
2 2023-01-03  Widget      9       36.50
3 2023-01-04    Tool      2       22.47
4 2023-01-05    Tool     15       30.80
5 2023-01-06  Widget      7       31.87
6 2023-01-07  Widget     12       17.39
7 2023-01-08    Tool      8       48.78
8 2023-01-09  Gadget     15       41.01
9 2023-01-10  Widget      3       47.58

In [42]:
sales["Total"] = sales["Units"] * sales["Unit_Price"]
print("Sales data with total:")
display(sales)

Sales data with total:

        Date Product  Units  Unit_Price   Total
0 2023-01-01  Widget     14       46.37  649.18
1 2023-01-02    Tool     18       20.35  366.30
2 2023-01-03  Widget      9       36.50  328.50
3 2023-01-04    Tool      2       22.47   44.94
4 2023-01-05    Tool     15       30.80  462.00
5 2023-01-06  Widget      7       31.87  223.09
6 2023-01-07  Widget     12       17.39  208.68
7 2023-01-08    Tool      8       48.78  390.24
8 2023-01-09  Gadget     15       41.01  615.15
9 2023-01-10  Widget      3       47.58  142.74

In [43]:
sales["Price_Category"] = sales["Unit_Price"].apply(
    lambda x: "High" if x > 30 else "Low")
print("\nWith price category:")
display(sales)

With price category:

        Date Product  Units  Unit_Price   Total Price_Category
0 2023-01-01  Widget     14       46.37  649.18           High
1 2023-01-02    Tool     18       20.35  366.30            Low
2 2023-01-03  Widget      9       36.50  328.50           High
3 2023-01-04    Tool      2       22.47   44.94            Low
4 2023-01-05    Tool     15       30.80  462.00           High
5 2023-01-06  Widget      7       31.87  223.09           High
6 2023-01-07  Widget     12       17.39  208.68            Low
7 2023-01-08    Tool      8       48.78  390.24           High
8 2023-01-09  Gadget     15       41.01  615.15           High
9 2023-01-10  Widget      3       47.58  142.74           High

In [44]:
sales["Units_Bin"] = pd.cut(sales["Units"], 
                           bins=[0, 5, 10, 15, 20],
                           labels=["low", "medium", "high", "very high"])
print("\nWith binned units:")
display(sales)

With binned units:

        Date Product  Units  Unit_Price   Total Price_Category  Units_Bin
0 2023-01-01  Widget     14       46.37  649.18           High       high
1 2023-01-02    Tool     18       20.35  366.30            Low  very high
2 2023-01-03  Widget      9       36.50  328.50           High     medium
3 2023-01-04    Tool      2       22.47   44.94            Low        low
4 2023-01-05    Tool     15       30.80  462.00           High       high
5 2023-01-06  Widget      7       31.87  223.09           High     medium
6 2023-01-07  Widget     12       17.39  208.68            Low       high
7 2023-01-08    Tool      8       48.78  390.24           High     medium
8 2023-01-09  Gadget     15       41.01  615.15           High       high
9 2023-01-10  Widget      3       47.58  142.74           High        low

In [45]:
pivot = sales.pivot_table(index="Product", 
                         columns="Price_Category", 
                         values="Total",  
                         aggfunc="sum"


)
print("\nPivot table:")
display(pivot)

Pivot table:

Price_Category     High     Low
Product
Gadget           615.15     NaN
Tool             852.24  411.24
Widget          1343.51  208.68